env:
  browser: true
  node: true

parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    jsx: true

extends:
  - airbnb
  - plugin:prettier/recommended

plugins:
  - prettier

rules:
  prettier/prettier: error
  global-require: off
  import/no-unresolved: off
